version: '3'

services:
  weight-tracker:
    build: .
    # Alternatively, use a pre-built image:
    # image: calomal/weight-tracker
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - FLASK_DEBUG=false
      - PORT=8080
      - LOG_LEVEL=INFO
      # Add user ID and group ID environment variables for UnRAID compatibility
      - PUID=99
      - PGID=100
    restart: unless-stopped
    # Add user namespace mapping for UnRAID
    user: "99:100"
    # Add UnRAID WebUI labels
    labels:
      - "org.opencontainers.image.title=Weight Tracker"
      - "org.opencontainers.image.description=A simple weight tracking application"
      - "org.opencontainers.image.authors=CalumMallorie"
      - "org.opencontainers.image.url=https://github.com/calummallorie/weight-tracker"
      - "io.unraid.webui=http://[IP]:[PORT:8080]"
      - "io.unraid.icon=https://raw.githubusercontent.com/calummallorie/weight-tracker/main/unraid_icon.png" 