version: '3'

services:
  weight-tracker:
    build: .
    # Alternatively, use a pre-built image:
    # image: calomal/weight-tracker
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./instance:/app/instance
    environment:
      - FLASK_DEBUG=false
      - PORT=8080
      - LOG_LEVEL=INFO
      - INSTANCE_PATH=/app/instance
    restart: unless-stopped
    # Add UnRAID-specific labels for WebUI
    labels:
      - "com.unraid.template.icon=https://raw.githubusercontent.com/CalumMallorie/weight-tracker/main/unraid_icon.png"
      - "com.unraid.template.webui=http://[IP]:[PORT:8080]/"
      - "org.opencontainers.image.title=Weight Tracker"
      - "org.opencontainers.image.description=A simple weight tracking application"
      - "org.opencontainers.image.authors=CalumMallorie"
      - "org.opencontainers.image.url=https://github.com/calummallorie/weight-tracker"
      - "io.unraid.webui=http://[IP]:[PORT:8080]"
      - "io.unraid.icon=https://raw.githubusercontent.com/calummallorie/weight-tracker/main/unraid_icon.png" 