version: '3'

services:
  weight-tracker:
    build: .
    # Alternatively, use a pre-built image:
    # image: calomal/weight-tracker
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - FLASK_DEBUG=false
      - PORT=8080
      - LOG_LEVEL=INFO
      # Add user ID and group ID environment variables for UnRAID compatibility
      - PUID=99
      - PGID=100
    restart: unless-stopped
    # Add user namespace mapping for UnRAID
    user: "99:100" 